import "~/styles/globals.css";

import { type Metadata } from "next";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <div className="flex w-[350px] flex-col gap-8">
        <Link
          href="/"
          className="flex items-center self-start text-2xl font-semibold"
        >
          <ChevronLeft className="h-8 w-8" />
          Back
        </Link>
        {children}
      </div>
    </div>
  );
}
